spring.application.name=ia-orchestrator
spring.rabbitmq.template.reply-timeout=120000

# Connexion à PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_orchestrator
spring.datasource.username=juve
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true